apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ein-api-experimental
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-einnsyn
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ein-api-experimental-api
  description: API Description
spec:
  type: openapi
  lifecycle: experimental
  owner: team-einnsyn
  system: einnsyn
  definition: |
    openapi: 3.1.0
    info:
      title: Example API
      version: 1.0.0
    paths:
      /users:
        get:
          summary: List users
          responses:
            '200':
              description: OK
    components:
      schemas:
        User:
          type: object
