name: Build/publish Docker image

on:
  workflow_dispatch:

jobs:
  call-workflow-image-build-publish:
    uses: felleslosninger/eid-github-workflows/.github/workflows/spring-boot-build-publish-image.yml@main
    with:
      java-version: 17
      allure-enabled: false
    secrets:
      eid-build-token: ${{ secrets.EID_BUILD_PAT }}
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}
      registry-url: ${{ secrets.REGISTRY_URL }}
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      allure-user: ${{ secrets.ALLURE_USER }}
      allure-password: ${{ secrets.ALLURE_PASSWORD }}
