name: Test and Coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-and-coverage:
    permissions:
      contents: read
      statuses: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
          server-id: 'github'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Check code formatting
        run: mvn spotless:check
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Pull testcontainer images
        run: >-
          docker pull 'docker.elastic.co/elasticsearch/elasticsearch:9.3.2'
          && docker pull 'postgres:16.3'
          && docker pull 'testcontainers/ryuk:0.12.0'

      - name: Run tests with coverage
        run: mvn clean test
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          fail-on-error: false

  container-scan:
    permissions:
      contents: read
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-container-scan.yml@main
    with:
      java-version: 25
      trivy-os-disable-scan: true
    secrets: inherit
